### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by DanBurkhardt** [MSmithDev/AirAPI_Windows#2]
Hello folks, could you please [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to this project repo? Preferably an MIT license so any forks are free to do whatever. If not, can you please confirm what common license applies?

Thanks and amazing work, I‘m working on a port to another platform & will contribute any useful changes.

**Comment by MSmithDev** [comment]
Thanks!

 Its been really great working with other members of the community. I hope it works well for you, the biggest thing that needs to be done is tuning the fusion algorithm because it tends to drift around yaw a bit and we havent inegrated the magnetometer because it made it worse. If you come aross any imrovements please share them!

Anyways, Added the license, Thanks again!

Add license - #3

**Comment by DanBurkhardt** [comment]
Absolutely. I'm actually packaging something up right now for a draft PR and I will issue it tonight.

It's not fusion, but I think you and many others may like what I've done here quite a lot (although I may need some &pointers on potential c++ fax pas')

Thanks, 
Dan
