### ISSUE TITLE
Where did you get the payload from to retrieve gyroscope data?

### ISSUE THREAD

**Issue by TheJackiMonster** [MSmithDev/AirAPI_Windows#4]
I was looking into your source code and I've seen this payload you send first to receive data from the interface providing orientation data. It seems to be necessary from my testing on Linux (the interface won't provide anything without it). However I don't get it to work with this payload in Python using libusb (unsure why though).

Is there any more detailed information I could look into? I want to try writing a user-space driver which can be used on devices like the Steam Deck to use orientation data with the nreal Air, so the screen isn't virtually glued to your head.

The best I could currently do was reverse-engineering different bytes in the data stream I get from the interface with number 4 which you use to retrieve the brightness. For example it's possible to track whether the display is turned on/off and still receive input events from the buttons while the screen is off by my own testing. ^^

**Comment by MSmithDev** [comment]
Hi Jack,

The payload is necessary to start IMU polling every time the glasses are power cycled. We discovered this while capturing USB packets from nebula and reverse engineering what we could from that. If you are fimiliar with Wireshark it should be fairly easy to capture USB packets on Linux. You want to make sure that the command sent matches the payload exactly. I noticed on windows using HIDAPI I had to add an extra 0x00 at the beginning because  it represents report ID on windows. You may have to remove this and that might be why its not working with libusb.

This is the payload im refering to on line 423 
`uint8_t magic_payload[] = { 0x00, 0xaa, 0xc5, 0xd1, 0x21, 0x42, 0x04, 0x00, 0x19, 0x01 };`

This first 0x00 may or may not be needed for you.

**Comment by TheJackiMonster** [comment]
> This is the payload im refering to on line 423 `uint8_t magic_payload[] = { 0x00, 0xaa, 0xc5, 0xd1, 0x21, 0x42, 0x04, 0x00, 0x19, 0x01 };`
> 
> This first 0x00 may or may not be needed for you.

OMG, removing that first byte worked. Thank you very much! ^^

Okay, I think I'm gonna write something in C now because that makes it easier to deal with such packed data.

**Comment by MSmithDev** [comment]
Awesome glad it worked for you!

Yeah we haven't had much time to clean it up. Mainly because we haven't fixed the yaw drift. Can't wait to see what you do with it!

**Comment by TheJackiMonster** [comment]
I've now published my code so far here:
https://gitlab.com/TheJackiMonster/nrealAirLinuxDriver

It might be interesting for you as well that I've managed to parse magnetometer data from the interface (at least I assume that's it - 3 components, each 16bit). Maybe that helps with stability and drift issues. ^^

**Comment by MSmithDev** [comment]
I messaged you on discord would be easier to discuss the mag stuff, we were aware of it but I believe we tried using it and it made things a bit worse. If it seemed to work better with it maybe we did something wrong haha.
